# Generated by Django 3.1.7 on 2021-03-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_auto_20210319_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
